# Generated by Django 4.2.13 on 2024-06-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiapp', '0003_carplate_wrongparking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
