# Generated by Django 4.2.13 on 2024-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moiapp', '0004_drone'),
    ]

    operations = [
        migrations.AddField(
            model_name='carplate',
            name='car_color',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='carplate',
            name='car_model',
            field=models.CharField(default='unknown', max_length=300),
        ),
    ]
